#!/usr/bin/python3
import re
import sys
import unicodedata
import os
import time

try:
    import pysrt
except:
    print('Missing dependency: pip3 install --user pysrt')
    exit(2)
try:
    import chardet
except:
    print('Missing dependency: pip3 install --user chardet')
    exit(2)

ADS = ['[###]',
       '.*a Card Shark AMERICASCARDROOM.*',
       '.*OpenSubtitles.*',
       '.*Advertise your product or brand here.*',
       '.*Apóyanos y conviértete en miembro VIP Para.*',
       '.*Addic7ed.*',
       '.*argenteam.*',
       '.*AllSubs.*',
       'Created and Encoded by.*',
       '.*corrected.*by.*',
       '.*Entre a AmericasCardroom. com Hoy.*',
       '.*Everyone is intimidated by a shark. Become.*',
       '.*Juegue Poker en Línea por Dinero Real.*',
       '.*OpenSubtitles.*',
       '.*Open Subtitles.*',
       '.*MKV Player.*',
       '.*MKV player.*',
       '.*Resync.*for.*',
       '.*Resync.*improved.*',
       '.*Ripped?By.*',
       '.*Sigue "Community" en.*',
       '.*Subtitles.*by.*',
       '.*Subt?tulos.*por.*',
       '.*Support us and become VIP member.*',
       '.*Subs.*Team.*',
       '.*subscene.*',
       '.*Subtitulado por.*',
       '.*subtitulamos.*',
       '.*Synchronized.*by.*',
       '.*Sincronizado y corregido por.*',
       '.*subdivx.*',
       '.*Sync.*Corrected.*',
       '.*Sync.*corrections.*by.*',
       '.*sync and corrections by.*'
       '.*Sync.*by.*',
       '.*Una.*traducci?n.*de.*',
       '.*tvsubtitles.*',
       '.*Una.*traducci?n.*de.*',
       'Tacho8',
       '.*www. com.*',
       '.*www. es.*'
]

def ads_in_line(line):
    for pt in ADS:
        if re.match(pt, line, re.DOTALL):
            return True
    return False

def slugify(value, allow_unicode=False):
    """
    Taken from https://github.com/django/django/blob/master/django/utils/text.py
    Convert to ASCII if 'allow_unicode' is False. Convert spaces or repeated
    dashes to single dashes. Remove characters that aren't alphanumerics,
    underscores, or hyphens. Convert to lowercase. Also strip leading and
    trailing whitespace, dashes, and underscores.
    """
    value = str(value)
    if allow_unicode:
        value = unicodedata.normalize('NFKC', value)
    else:
        value = unicodedata.normalize('NFKD', value).encode('ascii', 'ignore').decode('ascii')
    value = re.sub(r'[^\w\s-]', '', value.lower())
    return re.sub(r'[-\s]+', '-', value).strip('-_')

if __name__ == '__main__':
    from sys import argv
    from shutil import move

    print("starting script")
    for filename in sys.stdin:
        #filename = "\"" + filename + "\""
        try:
            filename = filename.strip()
            #print("Analyzing:", filename)
            created = os.path.getctime(filename)
            alreadyProcessed = time.mktime(time.strptime('2020-03-25 00:00:00', '%Y-%m-%d %H:%M:%S'))
            if created > alreadyProcessed:
                print("already processed " + filename)
                continue
            else:
                print("Analyzing:", filename)

            with open(filename, 'rb') as f:
                encoding = chardet.detect(f.read())
            encoding = encoding['encoding']
            subs = pysrt.open(filename, encoding=encoding)
            modified = False
            for i, line in enumerate(subs):
                if ads_in_line(line.text):
                    print("Removing: "+str(line)+"\n")
                    del subs[i]
                    modified = True
            if modified:
                #move(filename, filename+'.bak')
                subs.save(filename)
        except:
            continue
    print ("done")
